name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync Files to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 📂 Upload Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: laravel_core/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.*
