name: Deploy to cPanel

on:
  push:
    branches:
      - main # Jalankan otomatis saat ada push ke branch main (sesuaikan jika nama branch Anda 'master')

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Executing Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/laravel_core
            git pull origin main
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
